### ISSUE TITLE
Front End Updates

### ISSUE THREAD

**Issue by 0xAkrasia** [0xAkrasia/Keynesian-Beauty-Contest#5]
- [x] Remove whitespace at the top when a user scrolls up.
- [ ] Add privy wallet integration. see: https://github.com/0xAkrasia/In-Theory-Games/blob/main/src/components/ConnectSubmit/ConnectSubmit.tsx, https://github.com/0xAkrasia/In-Theory-Games/blob/main/src/main.tsx and Privy docs.
- [ ] Add faucet for new wallets without INCO. see: https://github.com/0xAkrasia/In-Theory-Games/blob/main/src/components/Faucet/Faucet.tsx.
- [x] Add an orange outline for selected faces to increase contrast (in design).
- [x] Change top text to "Select the four most popular faces from the crowd to win the pot." and remove 'Select 4 faces to bet'.
- [x] The landing page should show only the 'Submit' button.
- [x] If a user has already submitted an entry, the front end should show only the 'View your vote' button.
- [x] when 'View your vote' is called, the contestants you chose should be selected instead of spitting out a binary notification.
- [x] Change the font on text, numbers, and buttons to match the design.
- [ ] Change the style of the connect wallet button to match the design.
![Keynesian Beauty Contest Kenny #3](https://github.com/0xAkrasia/Keynesian-Beauty-Contest/assets/115685790/a118c27d-d717-4598-8382-34068454a77c)

**Comment by cryptitalk** [comment]
will do selected items today, rest will be done tomorrow.

**Comment by cryptitalk** [comment]
I created a separate branch `privy` to add the wallet and faucet, I think I need a whole week to understand this wallet implementation.

**Comment by cryptitalk** [comment]
stable version is at: https://keyn-wjaxre4ena-uc.a.run.app
